# Generated by Django 3.0.3 on 2020-03-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='l_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database_manager.laptop_properties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='u_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database_manager.Users'),
            preserve_default=False,
        ),
    ]
